### ISSUE TITLE
Opera extension

### ISSUE THREAD

**Issue by mishanthrop** [baoweb/modx-queeg#1]
Hi. 
Can you make extension for Chromium-based Opera?

**Comment by bartholomej** [comment]
Consider it done ;)
Opera extension is submitted but the moderation process has not started yet.
I'll let you know when ready.

**Comment by mishanthrop** [comment]
Thank you, I look forward to.

**Comment by bartholomej** [comment]
... and here it is https://addons.opera.com/en/extensions/details/modx-queeg/?display=en Looking forward for some feedback ;)

**Comment by mishanthrop** [comment]
Awesome, already installed. Thanks!
