### ISSUE TITLE
$lang = $userSettings['manager_language'];

### ISSUE THREAD

**Issue by mishanthrop** [baoweb/modx-queeg#2]
Error in plugin:
`$lang = $userSettings['manager_language'];`

> [OnWebPagePrerender]
> Notice: Undefined index: manager_language in /var/www/xxx/data/www/xxx.ru/core/cache/includes/elements/modplugin/14.include.cache.php on line 23

**Comment by bartholomej** [comment]
Ok, try this update and let me know ;) https://www.dropbox.com/s/myodo9tprxtpwyh/queeg-1.2.2-pl.transport.zip?dl=1
