### ISSUE TITLE
Feature Request: Timing tags

### ISSUE THREAD

**Issue by mishanthrop** [baoweb/modx-queeg#4]
Usually I add HTML comment in page like that:

```
<!-- [^q^] [^t^] -->
```

What do you think about adding this information in extra/extension? This feature may be optional.
From MODX documentation:

> [^q^] - Query Count -Shows how many database queries MODX made
> [^t^] - Total Time - Shows the total time taken to parse/ render the page

**Comment by bartholomej** [comment]
Merged in PR #9 ;) Thanks @mishantrop
