### ISSUE TITLE
Feature Request: Custom manager url

### ISSUE THREAD

**Issue by mishanthrop** [baoweb/modx-queeg#8]
It would be awesome to setup custom manager path for websites ("manager" is default for guest). 
[https://docs.modx.com/revolution/2.x/administering-your-site/security/hardening-modx-revolution#HardeningMODXRevolution-manager](https://docs.modx.com/revolution/2.x/administering-your-site/security/hardening-modx-revolution#HardeningMODXRevolution-manager)
Options page can contains table with relations «host - manager_url».
![queeg-optios](https://cloud.githubusercontent.com/assets/5341208/20511158/de240524-b086-11e6-8a30-decddb63c70e.png)

**Comment by bartholomej** [comment]
Hi @mishantrop, thanks for you feature request but this works automatically for all modx installations even for _custom manager urls_.
Every meta information from Queeg contains also _manager path_ as you can see here:
```html
<meta name='queeg' content='{"ID":6,"Published":0,"Edit Date":2015-12-11 10:20,"editedby":"admin","Resource&apos;s title":"test2","Alias":"index"}' data-system='{"id":6,"published":0,"host":"http:\/\/bartweb.cz","manager":"\/secret-administration\/"}' data-api='1' />
```

And if you are curious how it works, this is the whole magic ;)
https://github.com/baoweb/modx-queeg/blob/master/core/components/queeg/elements/plugins/queeg.plugin.php#L95

**Comment by mishanthrop** [comment]
@bartholomej but it works for logged in users only. Anonymous users will be redirected to /manager.

**Comment by bartholomej** [comment]
@mishantrop You're right but it is for security reasons. You don't want to expose custom manager url for anonymous attackers, do you? ;)

**Comment by mishanthrop** [comment]
I meant keeping the table locally. 

Reason:
For each website I use random manager url. Sometimes I forget manager url for concrete website and I need to look at my "database" of access information for websites. Also I am so lazy to type manually manager url after website domain.
Thats why I want just to click on extension icon and navigate to `site.ru/secure-manager-page`

> You don't want to expose custom manager url for anonymous attackers, do you? ;)

It is a local table, stored inside browser extension.

I can help with code, if it is reasonable.

**Comment by bartholomej** [comment]
I see. Well, if this is your big issue and you want to help with coding, it could be interesting new feature ;)
But PR is very welcome in this extension repository: https://github.com/bartholomej/modx-manager-switch
